### ISSUE TITLE
What is the root of the certificate chain?

### ISSUE THREAD

**Issue by dimakuv** [edgelesssys/marblerun.sh#38]
There seems to be inconsistency in your documentation.

Through the documentation, I had a feeling that the certificate chain is rooted in a self-signed certificate generated by the Coordinator service (and from what I understand, this root certificate is also ephemeral, i.e., it is not stored on the disk and always generated anew at each Coordinator startup).

However, you have this line in `attestation.md` file: https://github.com/edgelesssys/marblerun.sh/blame/main/content/docs/features/attestation.md#L22

It says `The chain ends at the root certificate authority (CA) of the provider of the secure hardware, which currently in almost all cases will be Intel.`

So according to this passage, it looks like the Coordinator is re-distributing the Intel certificates (the Intel Provisioning DCAP/ECDSA certificates). But then it doesn't sound right -- how could the Coordinator add itself to this Intel cert chain? The Coordinator would need to send a certificate request to the Intel PCS service, and somehow Intel would recognize it and produce+sign the certificate.

So what is the actual certificate chain that is sent to the end user (the client)? And how do you incorporate the Intel Provisioning certificates in this chain? (If this helps, Graphene's RA-TLS component has a helpful diagram explaining how it is done for Graphene: https://graphene.readthedocs.io/en/latest/attestation.html#mid-level-ra-tls-interface. Is your solution similar?).

**Comment by m1ghtym0** [comment]
Hi @dimakuv,
thanks for reaching out! This sentence is indeed confusing. We'll replace it with something more verbose and less ambiguous.
To answer your question:

> Through the documentation, I had a feeling that the certificate chain is rooted in a self-signed certificate generated by the Coordinator service

This is correct. The chain is rooted in a self-signed certificate generated by the Coordinator.
Similar to RA-TLS in Graphene the Coordinator obtains a quote on the hash of this certificate (it's the pub key for Graphene).
This is how the quote is bound to the certificate.
The sentenced tried to express that the chain of trust goes "Coordinator Certificate"->"SGX Quote"->"Intel certificates",
 ultimate ending in Intel's root certificate for SGX.

Note, the Coordinator's certificate does not contain the quote as a payload directly (!= Graphene).
Instead, the quote and certificate are obtained as two separate entities.
There is no particular reason for this and if that's something of interest we can add it.
In fact, EGo already has support for it: https://pkg.go.dev/github.com/edgelesssys/ego@v0.2.1/enclave#CreateAttestationServerTLSConfig

> (and from what I understand, this root certificate is also ephemeral, i.e., it is not stored on the disk and always generated anew at each Coordinator startup

This is not entirely correct. The Coordinator seals its encrypted state to disk for persistence. The state contains the private key and certificate. On startup, if no sealed state is found, a fresh key pair and certificate are generated.

**Comment by m1ghtym0** [comment]
Closing this with https://github.com/edgelesssys/marblerun.sh/pull/48
